### ISSUE TITLE
Background dark in gvim?

### ISSUE THREAD

**Issue by dynnamitt** [ninja/sky#1]
Possible?

set background=dark has no effect...

**Comment by uipoet** [comment]
The normal background color is set to none to inherit whatever background color is set in your terminal. This allows for transparency in iTerm on Mac OS X.

To specify your own background color, black for example, add this to your configuration:

``` vim
hi Normal gui=NONE guifg=#e0e0e0 guibg=#000000 cterm=NONE ctermfg=188 ctermbg=00
```
